### ISSUE TITLE
How to use this in a JS backend?

### ISSUE THREAD

**Issue by Wamy-Dev** [Dmbob/plex-oauth#18]
I am wanting to use this in my backend in JS. How would I do it using this library?

**Comment by Dmbob** [comment]
Hi,

You can use this library in your back end, however, you would still need to generate a request URL and send it to the front end for a user to sign in.

As far as I am aware, Plex does not have the capability of creating an OAuth client and providing a client id/client secret that you can use to authenticate a system rather than a user.

In order to retrieve an authentication token, you usually need to manually sign into Plex at least once: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

Please let me know if this answers your question. If it does, please close this issue.

Thank you

**Comment by Wamy-Dev** [comment]
I found a library that works very well for anyone in the future that needs it for a backend. https://github.com/kylmp/Login-With-Plex

**Comment by Dmbob** [comment]
Hi @Wamy-Dev,

I think I may have misunderstood your original question. based on the library that you found, you can do the same with `plex-oauth`. Using a similar example:

Create an instance of the `PlexOauth` class:
```javascript
const plexOauth = new PlexOauth({
	clientIdentifier: "<PROVIDE_UNIQUE_VALUE>",
	product: "<NAME_OF_YOUR_APP>",
	device: "<NAME_OF_YOUR_DEVICE>",
	version: "1",
	forwardUrl: "https://localhost:3000",
	platform: "Web",
	urlencode: true
});
```

Redirect user to the Oauth login page:
```javascript
App.get('/login', async function(req, res) { 
	// Generate OAuth URL and Pin
	const [hostedUILink, pinId] = await plexOauth.requestHostedLoginURL();

	// Save Pin in session
	req.session.pinId = pinId;

	// Reduirect to the OAuth URL for authentication
	res.redirect(hostedUILink);
})
```

Store auth token and redirect to your application:
```javascript
App.get('/redirect', async function(req, res) {
	// Get the auth token	
	const authToken = await plexOauth.checkForAuthToken(req.session.pinId);

	// Save the auth token to the session
	req.session.authToken = authToken;
  
	// Delete Pin that is no longer required
	req.session.plexUser = plexUserInfo;
	delete req.session.pinId;
  
	// Redirect to your app
	res.redirect('/app');
})
```

Please let me know if this works for you, or if you have any trouble.

Thank you!

**Comment by Wamy-Dev** [comment]
Does it fix this problem. I will move to this library if I dont get this error ![image](https://user-images.githubusercontent.com/25761442/182520447-b06c1646-8a19-44d7-aa25-780ef3652d0b.jpeg)
